# Generated by Django 2.0.6 on 2018-06-22 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SmallEngineClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(max_length=2000)),
                ('street_address', models.CharField(max_length=2000)),
                ('city', models.CharField(max_length=2000)),
                ('session_1_date', models.DateTimeField()),
                ('session_2_date', models.DateTimeField()),
                ('paid_students', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Small Engine Classes',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.EmailField(blank=True, max_length=200, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
    ]
