# Generated by Django 2.0.6 on 2018-06-22 02:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smallengineclasses', '0002_student_class_updates'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='smallengineclass',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='smallengineclasses.SmallEngineClass'),
        ),
        migrations.AlterField(
            model_name='student',
            name='class_updates',
            field=models.BooleanField(default=False, verbose_name='Receive updates on new classes?'),
        ),
    ]
