# Generated by Django 2.0.6 on 2018-06-22 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smallengineclasses', '0003_auto_20180621_2027'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='smallengineclass',
            name='paid_students',
        ),
    ]
