# Generated by Django 2.0.6 on 2018-06-06 22:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lname', models.CharField(help_text='Last name', max_length=200)),
                ('fname', models.CharField(help_text='First name', max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('phonenumber', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='LawnMower',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=200)),
                ('enginemodel', models.CharField(help_text='model number of the engine', max_length=200)),
                ('chassismodel', models.CharField(help_text='model number of the chassis', max_length=200)),
                ('serialnumber', models.CharField(help_text='serial number', max_length=200)),
                ('sparkplug', models.CharField(max_length=200)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('cost', models.CharField(help_text='actual charge for service', max_length=200)),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(help_text='name of the service', max_length=200)),
                ('cost', models.CharField(help_text='general cost for service', max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='serviceinstance',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.ServiceType'),
        ),
        migrations.AddField(
            model_name='lawnmower',
            name='servicerecord',
            field=models.ManyToManyField(to='catalog.ServiceInstance'),
        ),
    ]
