# Generated by Django 2.0.6 on 2018-06-06 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='fname',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='lname',
            new_name='last_name',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='phonenumber',
            new_name='phone_number',
        ),
    ]
