# Generated by Django 2.0.6 on 2018-06-06 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20180606_1701'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lawnmower',
            old_name='chassismodel',
            new_name='chassis_model',
        ),
        migrations.RenameField(
            model_name='lawnmower',
            old_name='enginemodel',
            new_name='engine_model',
        ),
        migrations.RenameField(
            model_name='lawnmower',
            old_name='serialnumber',
            new_name='serial_number',
        ),
        migrations.RenameField(
            model_name='lawnmower',
            old_name='servicerecord',
            new_name='service_record',
        ),
        migrations.RenameField(
            model_name='lawnmower',
            old_name='sparkplug',
            new_name='spark_plug',
        ),
    ]
