# Generated by Django 2.0.6 on 2018-06-07 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20180606_1723'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicetype',
            old_name='cost',
            new_name='price',
        ),
        migrations.AlterField(
            model_name='servicetype',
            name='description',
            field=models.TextField(blank=True, help_text='what it includes', max_length=2000),
        ),
    ]
