# Generated by Django 2.0.6 on 2018-06-08 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_auto_20180606_1814'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForSale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=200)),
                ('picture', models.ImageField(upload_to='')),
                ('price', models.CharField(max_length=20)),
            ],
        ),
    ]
