# Generated by Django 2.0.6 on 2018-06-11 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_forsale'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='forsale',
            options={'verbose_name_plural': 'For Sale'},
        ),
        migrations.AlterField(
            model_name='forsale',
            name='picture',
            field=models.ImageField(upload_to='gallery'),
        ),
    ]
