# Generated by Django 2.0.6 on 2018-06-17 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_auto_20180611_1223'),
    ]

    operations = [
        migrations.AddField(
            model_name='forsale',
            name='sold',
            field=models.BooleanField(default=False),
        ),
    ]
