# Generated by Django 2.0.6 on 2018-06-17 22:04

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_forsale_sold'),
    ]

    operations = [
        migrations.RenameField(
            model_name='forsale',
            old_name='price',
            new_name='list_price',
        ),
        migrations.RemoveField(
            model_name='forsale',
            name='sold',
        ),
        migrations.AddField(
            model_name='forsale',
            name='list_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='forsale',
            name='sale_customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.Customer'),
        ),
        migrations.AddField(
            model_name='forsale',
            name='sale_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='forsale',
            name='sale_price',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
