# Generated by Django 2.0.6 on 2018-06-18 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_auto_20180618_1227'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ForSale',
            new_name='SaleListing',
        ),
        migrations.AlterModelOptions(
            name='salelisting',
            options={},
        ),
    ]
