# Generated by Django 2.0.6 on 2018-06-19 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_auto_20180618_1231'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmallEngineClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.TextField(max_length=2000)),
                ('street_address', models.TextField(max_length=2000)),
                ('city', models.TextField(max_length=2000)),
                ('session_1_date', models.DateTimeField()),
                ('session_2_date', models.DateTimeField()),
                ('paid_students', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='servicetype',
            name='display_on_website',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
