# Generated by Django 2.0.6 on 2018-06-19 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_auto_20180618_2107'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='smallengineclass',
            options={'verbose_name_plural': 'Small Engine Classes'},
        ),
        migrations.AlterField(
            model_name='smallengineclass',
            name='city',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='smallengineclass',
            name='host',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='smallengineclass',
            name='street_address',
            field=models.CharField(max_length=2000),
        ),
    ]
