# Generated by Django 2.0.6 on 2018-06-19 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0015_auto_20180618_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smallengineclass',
            name='paid_students',
            field=models.IntegerField(default=0),
        ),
    ]
