# Generated by Django 2.0.6 on 2018-06-20 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    atomic=False

    dependencies = [
        ('catalog', '0016_auto_20180618_2113'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceinstance',
            name='lawn_mower',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.LawnMower'),
        ),
    ]
