# Generated by Django 2.0.6 on 2018-06-20 20:37

from django.db import migrations


class Migration(migrations.Migration):
    atomic=False

    dependencies = [
        ('catalog', '0017_serviceinstance_lawn_mower'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ServiceInstance',
            new_name='ServiceRecord',
        ),
        migrations.RemoveField(
            model_name='lawnmower',
            name='service_record',
        ),
    ]
