# Generated by Django 2.0.6 on 2018-06-20 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0018_auto_20180620_1437'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
