# Generated by Django 2.0.6 on 2018-06-20 20:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0019_serviceinstance'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceLineItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('cost', models.CharField(help_text='actual charge for service', max_length=200)),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.Employee')),
                ('lawn_mower', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.LawnMower')),
                ('service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.ServiceType')),
            ],
        ),
        migrations.RemoveField(
            model_name='servicerecord',
            name='cost',
        ),
        migrations.RemoveField(
            model_name='servicerecord',
            name='date',
        ),
        migrations.RemoveField(
            model_name='servicerecord',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='servicerecord',
            name='service',
        ),
    ]
