# Generated by Django 2.0.6 on 2018-06-20 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    atomic=False
    dependencies = [
        ('catalog', '0020_auto_20180620_1442'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ServiceInstance',
        ),
        migrations.RemoveField(
            model_name='servicelineitem',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='servicelineitem',
            name='lawn_mower',
        ),
        migrations.RemoveField(
            model_name='servicelineitem',
            name='service',
        ),
        migrations.AddField(
            model_name='servicerecord',
            name='cost',
            field=models.CharField(default=1, help_text='actual charge for service', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servicerecord',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servicerecord',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.Employee'),
        ),
        migrations.AddField(
            model_name='servicerecord',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.ServiceType'),
        ),
        migrations.DeleteModel(
            name='ServiceLineItem',
        ),
    ]
