# Generated by Django 2.0.6 on 2018-06-24 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0029_auto_20180621_2002'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lawnmower',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
